# -*- coding: utf-8 -*-
"""DCF2 Historical Analysis - INCLASS 0945.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1euvpDOoYVUET7_rLjIhLSzIg-qIPYc-Z

# DCF Part 2: Historical Analysis

In this notebook, we do historical analysis of our target firm. This is all backward looking.

The primary goal is to help us understand the firm's context which in turn helps us understand how to best make projections into the future. This is not the only analysis we need, but we do need it.

The focus will be on key valuation metrics:
* Growth Rates
* Margins
* Reinvestment

## Plan

1. Get Income Statement data: Revenue and EBIT. Compute growth rates in both for as long a history as we can (4 years for Yahoo)
2. Compute EBIT Margin (EBIT/Revenue) and Gross Margin (Gross Profit/Revenue)
3. Get Balance Sheet data to compute NWC and Change in NWC
4. Get Statement of Cash Flows to get Capital Expenditures and Depreciation & Amortization.
5. Compute Reinvestment = CapEx - D&A + Change in NWC
6. Compute FCF, NOPAT and Reinvestment Rate = Reinvestment/NOPAT


This is our in-class project that we will work on progressively through the mod.

Expectations:
1. Notebook is clean and neat, with no repeated code. It has clearly labeled sections for inputs/imports at the beginning. Code is sufficiently commented to demonstrate your understanding of the code and help you or anyone else who may use this code later. All numbers should be formatted so they are readable (so, use commas with large numbers, only a few decimal points).
2. All calculations are correct and all discussion questions are answered completely but concisely, demonstrating a depth of understanding.

Workflow:
1. Notebooks are inherently experimental and allow you to try things, however that requires some good habits
2. Once you are "done" in any sense, you always need to "clean up" your notebook to make it presentable. You'd do the same in Excel - you've tried lots of things, etc. but before you present it, you clean it up.
3. Finally, restart the Runtime/Kernel and run it cleanly all the way top to bottom one time.

Then, its ready to go.

## 1 Always put Imports and Installs at the beginning

And only put them in once.

Set display options here if you are using them.

Set API Keys here if you need them.
"""

# necessary imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm

import yfinance as yf

# Format setting for the model - tame the decimals!
pd.reset_option('display.float_format')
pd.set_option('display.float_format', lambda x: '{:,.2f}'.format(x))

# Set Ticker we are modeling
# Set Ticker we are modeling
ticker_symbol = 'MSFT'
company_name = "Microsoft"

eff_tax_rate = 0.19
marg_tax_rate = 0.25 # for WACC, given

# this is what we divide numbers by, 1000000 is $M
scale_factor = 1000000
scale_name = '$M'

"""## 2 Get Income Statement Data"""

# Create a Ticker object
ticker = yf.Ticker(ticker_symbol)

# Get annual income statement data, transpose and sort so numeric index is in correct order.
# OUTPUT should have 4 rows, one for each date and column names across the top are IS fields

income_statement = ticker.financials.T.sort_index()

# lots of data in this one, so print it out with .info()
income_statement.info()

# print key columns: Total Revenue, EBIT, Gross Profit
income_statement[['Total Revenue','EBIT','Gross Profit']]/scale_factor

"""### Compute Growth Rates and Margins"""

# Calculate Gross Margin
income_statement['Gross Margin'] = income_statement['Gross Profit']/income_statement['Total Revenue']

# Calculate EBIT Margin
income_statement['EBIT Margin'] = income_statement['EBIT']/income_statement['Total Revenue']

# Compute Revenue Growth, EBIT Growth
income_statement['Revenue Growth'] = income_statement['Total Revenue'].pct_change()
income_statement['EBIT Growth'] = income_statement['EBIT'].pct_change()

# Create a dataframe called df_stats that has the following:
# Revenue Growth, EBIT Growth, Gross Margin, EBIT Margin, Tax Rate for Calcs (eff tax rate) - column names. Rows are dates (year)
# How you do this may vary depending on how you did things above
df_stats = income_statement[['Revenue Growth','EBIT Growth','Gross Margin','EBIT Margin']].copy()
df_stats["Eff Tax Rate"] = income_statement['Tax Rate For Calcs']
# print it out
df_stats

"""## 3 Get Balance Sheet Data"""

# Repeat the above but with the balance sheet - get it, transpose so dates are rows, columns are fields
balance_sheet = ticker.balance_sheet.T.sort_index()

# again use .info() so you can see what you have
balance_sheet.info()

# print key columns for Non-Cash NWC: Current Assets, Current Liabilities, Cash, Current Debt
balance_sheet[['Current Assets','Current Liabilities','Cash Cash Equivalents And Short Term Investments','Current Debt And Capital Lease Obligation']].dropna()/scale_factor

"""### Compute NWC and Change in NWC"""

# Adjust Current Assets by subtracting Cash
balance_sheet["Adj CA"] = balance_sheet["Current Assets"] - balance_sheet["Cash Cash Equivalents And Short Term Investments"]

# Adjust Current Liabilities by subtracting Current Debt
balance_sheet["Adj CL"] = balance_sheet["Current Liabilities"] - balance_sheet["Current Debt And Capital Lease Obligation"]

# Calculate NWC = Adj CA - Adj CL
balance_sheet["NWC"] = balance_sheet["Adj CA"] - balance_sheet["Adj CL"]

# Calculate the Change in NWC
balance_sheet["Ch in NWC"] = balance_sheet["NWC"].diff()

# Create a new DataFrame with the required column
nwc_change_df = balance_sheet[["NWC", "Ch in NWC"]].copy()

# Display the new DataFrame
nwc_change_df/scale_factor

"""## 4 Get Statement of Cash Flows"""

# Repeat the above but with SCF
cash_flows = ticker.cashflow.T.sort_index()

# Reverse the sign of the 'Capital Expenditure' to make it positive (my personal preference - optional)
cash_flows['Capital Expenditure'] = -cash_flows['Capital Expenditure']

cash_flows

# print the .info()
cash_flows.info()

# print key columns - CapEx and D&A
cash_flows[['Capital Expenditure','Depreciation And Amortization']]/scale_factor

# merge cash_flows and nwc_change_df on the date index
merged_cash_flows = cash_flows.join(nwc_change_df)

# Display the merged DataFrame, showing CapEx, D&A and Ch in NWC
merged_cash_flows[['Capital Expenditure','Depreciation And Amortization','Ch in NWC']]/scale_factor

"""### Compute Reinvestment and NOPAT"""

# Calculate Reinvestment = CapEx - D&A + Ch in NWC
merged_cash_flows['Reinvestment'] = merged_cash_flows['Capital Expenditure'] - merged_cash_flows['Depreciation And Amortization'] + merged_cash_flows['Ch in NWC']

# Extract the 'Reinvestment' column to a new DataFrame
reinvestment_df = merged_cash_flows[['Reinvestment']].copy()

# Display the 'Reinvestment' DataFrame
reinvestment_df/scale_factor

# Calculate NOPAT in the income statement dataframe
income_statement['NOPAT'] = income_statement['EBIT']*(1-df_stats['Eff Tax Rate'])

# Extract the 'NOPAT' column to a new DataFrame
nopat_df_temp = income_statement[['NOPAT']].copy()

# Display the 'NOPAT' DataFrame
nopat_df_temp/scale_factor

"""## 5 Compute Reinvestment Rate"""

# Calculate Reinvestment Rate = Reinvestment/NOPAT

# merge in nopat_df and reinvestment_df (I kept it all in nopat_df)
nopat_df = nopat_df_temp.join(reinvestment_df)

# compute reinvestment rate
nopat_df['Reinv Rate'] = nopat_df['Reinvestment']/nopat_df['NOPAT']

# Now, let's display the updated DataFrame with all the required information
nopat_df

"""## 6 Final Result"""

# now merge in the new Reinvestment Rate column into df_stats
df_stats = df_stats.join(nopat_df['Reinv Rate'])

# print it out
df_stats

"""## Homework

Compute EBITDA Margin

Output is a dataframe with a column called "EBITDA Margin" (there can be other columns also, but be sure to show this one by itself)
"""



