# -*- coding: utf-8 -*-
"""DCF3 DCF Model - INCLASS 0945.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fQ5JCtO9aa-5FdsFOrUw9mGfbU_XickI

# DCF Part 3: Final Model

Here we bring it all together. The end goal here is to get a DCF model-implied share price.

Plan:

1. Start with LTM data to get the most recent starting point
2. Use assumptions about projections. These will be hardcoded up front, including projected revenue growth, margins, and reinvestment rate. All must be for the same number of years in the future.
3. Create projections dataframe such that Year 1 is 12 months from the LTM data we just retrieved.
4. Use projected ratios to generate $-value projections from Revenue to NOPAT to FCF.
5. Discount FCF to the present
6. Compute Terminal Value using Gordon Growth Model, Discount to PV
7. Compute model-implied firm value and compute share price

This is our in-class project that we will work on progressively through the mod.

Expectations:
1. Notebook is clean and neat, with no repeated code. It has clearly labeled sections for inputs/imports at the beginning. Code is sufficiently commented to demonstrate your understanding of the code and help you or anyone else who may use this code later. All numbers should be formatted so they are readable (so, use commas with large numbers, only a few decimal points).
2. All calculations are correct and all discussion questions are answered completely but concisely, demonstrating a depth of understanding.

Workflow:
1. Notebooks are inherently experimental and allow you to try things, however that requires some good habits
2. Once you are "done" in any sense, you always need to "clean up" your notebook to make it presentable. You'd do the same in Excel - you've tried lots of things, etc. but before you present it, you clean it up.
3. Finally, restart the Runtime/Kernel and run it cleanly all the way top to bottom one time.

Then, its ready to go.

# Always put Imports and Installs at the beginning

And only put them in once.

Set display options here if you are using them.

Set API Keys here if you need them.
"""

# necessary imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm

import yfinance as yf

# Set Ticker we are modeling
# Set Ticker we are modeling
ticker_symbol = 'MSFT'
company_name = "Microsoft"

eff_tax_rate = 0.19
marg_tax_rate = 0.25 # for WACC, given

# this is what we divide numbers by, 1000000 is $M
scale_factor = 1000000
scale_name = '$M'

# Format setting for the model - tame the decimals!
pd.reset_option('display.float_format')
pd.set_option('display.float_format', lambda x: '{:,.2f}'.format(x))

"""## 1 Assumptions about Projection Patterns

This is a "minmimalist" model which means we only need the following:
1. Revenue Growth: To project Revenue
2. EBIT Margin: Go from Revenue to EBIT
3. Effective Tax Rate: Go from EBIT to NOPAT
4. Reinvestment Rate: Go from NOPAT to FCF


"""

ss_growth = 0.03
growth_pattern = [.20, .15, .15, .15, .10, 0.10, 0.10, 0.08, 0.08, 0.06] #must be list the same length as time_horizon

reinv_rate_pattern = [0.4, 0.4, 0.3, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2]
assert len(growth_pattern) == len(reinv_rate_pattern), "Time patterns do not match - Reinv Rate."

ebit_margin = [0.46, 0.46, 0.46, 0.46, 0.46, 0.46, 0.46, 0.46, 0.46, 0.46]
assert len(growth_pattern) == len(ebit_margin), "Time patterns do not match - EBIT."

time_horizon = len(growth_pattern)
print(f"Length of projection period: {len(growth_pattern)} years")

# Create a Ticker object
ticker = yf.Ticker(ticker_symbol)

# Get shares outstanding data
shares_outstanding = ticker.info['sharesOutstanding']

print(f"Shares Outstanding for {ticker_symbol}: {shares_outstanding/scale_factor:,.2f} {scale_name}")

"""## 2 Need LTM Data for starting point

Yahoo! Finance does not have LTM data - you need to create it yourself. Really all we need is LTM Revenue.
"""

# get LTM data from yfinance
ltm_data = ticker.quarterly_financials.T.sort_index()

# use .iloc to get the most recent 4 quarters of data only
ltm_data = ltm_data.iloc[-4:]

# print it out
ltm_data

# If you don't have it already, create this variable `ltm_revenue` that is a float (not dataframe), with only revenue, scaled.
ltm_revenue = ltm_data['Total Revenue'].sum() # in $ not scaled

print(f"Most Recent Revenue for {ticker_symbol}'s Quarterly Data(${scale_name}): {ltm_revenue/scale_factor:,.2f}")

# here is the most recent date from which we begin our projections - this should be a datetime data type (not a string or float or int, etc.)
most_recent_date = ltm_data.index[-1]

print(f"Most Recent Date for {ticker_symbol}'s Quarterly Data: {most_recent_date}")

"""## 3 Create dataframe for projections

This is just gathering our assumptions and using the right dates for them
"""

# GIVEN: Just run this code. This is a bit more advanced than I expect most of you can do
#        Feel free to paste it into ChatGPT for a more in-depth explanation.
# this cell gets the dates for our projections going forward

# first, a lookup dictionary that allows us to convert a numeric month to a specific code for datetime objects
# the "A" stands for annual, so these codes will generate Annual intervals starting in that month, which is our goal.
freq_dict = {1:'YE-JAN',2:'YE-FEB',3:'YE-MAR',4:'YE-APR', 5:'YE-MAY',6:'YE-JUN',
             7:'YE-JUL',8:'YE-AUG', 9:'YE-SEP',10:'YE-OCT',11:'YE-NOV',12:'YE-DEC'}

# most_recent_date.month is an integer 1-12 representing the month part of the date.
# So, can you tell what this does?
f = freq_dict[most_recent_date.month]
#print result
print(f"This should match month above for most recent month in the above code cell: {f}\n")

# Generate the new dates for the DataFrame, matching the "growth_pattern" list above
new_dates = pd.date_range(start=most_recent_date, periods=len(growth_pattern)+1, freq=f)

print(f"Dates going forward, starting with time 0:")
print(new_dates)
print("\n")

projections = pd.DataFrame(index=new_dates[1:], data={'Revenue Growth': growth_pattern,
                                                   'EBIT Margin': ebit_margin,
                                                   'Reinv Rate': reinv_rate_pattern})
projections

"""## 4 Now create projections in $"""

# Given LTM revenue and the revenue growth pattern (the python list above)
# generate the $M projections for revenue
# (this may take a few lines of code, not just one or two)
projected_revenue_list = [ltm_revenue]

# use a for loop to grow revenue according to the list growth_pattern
for i in range(len(growth_pattern)):
  new_revenue = projected_revenue_list[i] * (1 + growth_pattern[i])
  projected_revenue_list.append(new_revenue)

# remember, projected revenue also has one too many entries!!
# remove the first entry in the projected_revenue list, as the DataFrame index starts from the first projected year
projected_revenue_list.pop(0)

# Add the projections as columns to the projections DataFrame
# Pandas will convert the list to a Series and align it with the DataFrame's index
projections['Revenue'] = projected_revenue_list

# Now compute projected EBIT using the 'Revenue' column (which is now a Series)
# and the 'EBIT Margin' column (also a Series)
projections['EBIT'] = projections['Revenue'] * projections['EBIT Margin']

# Calculate projected NOPAT (Net Operating Profit After Tax)
# eff_tax_rate is a scalar, so it will broadcast correctly
projections['NOPAT'] = projections['EBIT'] * (1 - eff_tax_rate)

# Calculate the projected FCF
# 'Reinv Rate' is already a column in projections
projections['FCF'] = projections['NOPAT'] * (1 - projections['Reinv Rate'])

# for display purposes, create two lists of column names, one for metrics and one for $ values
metric_columns = ['Revenue Growth', 'EBIT Margin', 'Reinv Rate']
dollar_columns = ['Revenue', 'EBIT', 'NOPAT', 'FCF']

# print them out
projections[dollar_columns]/scale_factor

projections[metric_columns]

"""## 5 Get WACC from our WACC notebook

We did this already, so just need to import it.

I put the following prompt in ChatGPT:
```
take this data:

	WACC
0	7.67
1	8.72
2	9.77

and make it so I can turn it into a pandas dataframe if I paste the code
```
"""

# using our WACC notebook and some AI help, create a data frame for WACC.
# It should look like the dataframe shown above in the text block.
# It may take several lines of code.
data = {
    'WACC': [7.96, 9.25, 10.54]
}

wacc_df = pd.DataFrame(data)
print(wacc_df)

# Also, for a first pass, we need a single wacc, so set this float value:
wacc = wacc_df.iloc[1]['WACC'] / 100 # Convert percentage to decimal

print(f"WACC: {wacc:,.4f}")

"""## 6 Discount FCF to Present"""

# Calculate the present value of future cash flows
# Create a time period column starting from 1
projections['T'] = range(1, len(projections) + 1)

# Calculate the present value of each FCF
projections['Discounted_FCF'] = projections['FCF'] / (1 + wacc) ** projections['T']

# print
projections['Discounted_FCF']/scale_factor

"""## 7 PV of Terminal Value"""

# Calculate the terminal value using the Gordon Growth Model (also known as the Perpetuity Growth Model)
terminal_value = projections.iloc[-1]['FCF']*(1 + ss_growth) / (wacc - ss_growth)

print(f"TV for {ticker_symbol}: ({scale_name}) {terminal_value/scale_factor:,.2f}")

# discount it to the present
present_value_of_terminal = terminal_value / (1 + wacc) ** time_horizon

print(f"PV of TV for {ticker_symbol}: ({scale_name}) {present_value_of_terminal/scale_factor:,.2f}")

"""## 8 Firm Value and Share Price"""

# compute PV of firm value
firm_value = projections['Discounted_FCF'].sum() + present_value_of_terminal

print(f"Firm Value for {ticker_symbol}: ({scale_name}) {firm_value/scale_factor:,.2f}")

# compute share price
# get total debt from yahoo finance ticker object
total_debt = ticker.info['totalDebt']
# print out total_debt
print(f"Total Debt for {ticker_symbol}: ({scale_name}) {total_debt/scale_factor:,.2f}")
# get total cash from ticker object
total_cash = ticker.info['totalCash']
# print total cash
print(f"Total Cash for {ticker_symbol}: ({scale_name}) {total_cash/scale_factor:,.2f}")

# compute share price
share_price = (firm_value - total_debt + total_cash) / shares_outstanding

print(f"Share Price for {ticker_symbol}: ${share_price:,.2f}")

"""## 9 Visualizing Uncertainty

Let's take our upper and lower WACC to quantify the uncertainty in our share price estimate.

What you are doing here is creating a loop from what we just did:
1. Create a for loop that iterates through the three estimates of WACC
2. For each wacc, compute the PV of intermediate CFC, TV, PV of TV and share price
3. The output should be a list of share prices, upper, middle (what we just computed) and lower.

Its good to repeate the middle wacc calculation to validate it is the same as above.
"""

# write code here. This is likely a large block of code, maybe 20 lines or more

# iterate through the wacc_df dataframe:

stock_prices = []

for row in wacc_df.itertuples(index=False):
    wacc = row.WACC/100
    pv_FCF = sum(projections['FCF'] / (1 + wacc) ** projections['T'])

    terminal_value = projections.iloc[-1]['FCF']*(1 + ss_growth) / (wacc - ss_growth)

    present_value_of_terminal = terminal_value / (1 + wacc) ** time_horizon
    firm_value = pv_FCF + present_value_of_terminal

    share_price = (firm_value - total_debt + total_cash) / shares_outstanding
    print(f"Share Price for {ticker_symbol}: {share_price:,.2f}")

    stock_prices.append(share_price)

# output is three stock prices: upper, middle and lower
print(f"Stock Prices: {stock_prices}")

"""This is our AI generated code:"""

# List to store results
results = []

# Loop over each WACC in the DataFrame
for index, row in wacc_df.iterrows():
    # Convert WACC from percentage to decimal
    wacc = row['WACC'] / 100

    # Step 1: Discount the FCF to present
    projections['Discounted_FCF'] = projections['FCF'] / (1 + wacc) ** projections['T']

    # Step 2: Compute and discount the terminal value
    terminal_value = projections.iloc[-1]['FCF'] * (1 + ss_growth) / (wacc - ss_growth)
    present_value_of_terminal = terminal_value / (1 + wacc) ** time_horizon

    # Step 3: Compute firm value and share price
    firm_value = projections['Discounted_FCF'].sum() + present_value_of_terminal

    share_price = (firm_value - total_debt + total_cash) / shares_outstanding

    # Store results
    results.append({
        'WACC (%)': row['WACC'],
        'Share Price': share_price
    })

# Convert results to a DataFrame for easier analysis
share_price_df = pd.DataFrame(results)

# Print final result
print(share_price_df)

"""Now create a plot!

1. Get 1 year historical stock prices data for the `ticker`
2. Plot it
3. Also plot, as horizontal lines, the upper, middle, and lower stock price estimates
4. Shade the area between the upper and lower stock price

Be sure to use accurate and informative axis labels, plot titles, etc. with correct units.

"""

# Step 1: Fetch daily price data
ticker_data = yf.Ticker(ticker_symbol)
daily_data = ticker_data.history(period="1y")  # last year of daily data

# Step 2: Extract the share prices from the DataFrame (from previous step)
price_estimates = share_price_df['Share Price'].tolist()
price_labels = [f"WACC: {w:.2f}%" for w in share_price_df['WACC (%)']]

# Get top and bottom estimated prices
price_min = min(price_estimates)
price_max = max(price_estimates)

# Step 3: Plot
plt.figure(figsize=(12, 6))
plt.plot(daily_data.index, daily_data['Close'], label="Daily Close Price", color="black")

# Plot horizontal lines for each price estimate
for price, label in zip(price_estimates, price_labels):
    plt.axhline(y=price, linestyle='--', label=label)

# Shade area between lowest and highest estimated price
plt.axhspan(price_min, price_max, color='gray', alpha=0.2, label='Valuation Range')

# Labels and title
plt.title(f"Share Price vs Valuation Estimates for {company_name}")
plt.xlabel("Date")
plt.ylabel("Share Price ($)")
plt.ylim(bottom=0)  # Set lower y-limit to 0
plt.legend()
plt.grid(True)
plt.tight_layout()

# Show the plot
plt.show()

